from pptx.dml.color import RGBColor

# Dimensions & layout
SLIDE_WIDTH = 10  # inches
SLIDE_HEIGHT = 5.625  # inches
FOOTER_Y = 5.3
CONTENT_START_Y = 1.5
AVAILABLE_CONTENT_HEIGHT = FOOTER_Y - CONTENT_START_Y
MAIN_BULLET_INDENT = 0.5
SUB_BULLET_INDENT = 1.0
SUB_SUB_BULLET_INDENT = 1.5

THEME = {
    "use_gradients": True,
    "corner_accent": True,
    "slide_border": False,
    "content_box_shadow": True,
    "modern_bullets": True,
    "footer_style": "modern",  # "modern" or "classic"
}

COLORS = {
    "primary": RGBColor(37, 99, 235),
    "primary_light": RGBColor(96, 165, 250),
    "primary_dark": RGBColor(30, 64, 175),
    "secondary": RGBColor(79, 70, 229),
    "secondary_light": RGBColor(139, 92, 246),
    "secondary_dark": RGBColor(67, 56, 202),
    "accent1": RGBColor(139, 92, 246),
    "accent2": RGBColor(16, 185, 129),
    "accent3": RGBColor(245, 158, 11),
    "accent4": RGBColor(239, 68, 68),
    "light": RGBColor(243, 244, 246),
    "light_alt": RGBColor(249, 250, 251),
    "dark": RGBColor(31, 41, 55),
    "dark_alt": RGBColor(17, 24, 39),
    "text": RGBColor(17, 24, 39),
    "text_light": RGBColor(255, 255, 255),
    "text_muted": RGBColor(107, 114, 128),
    "success": RGBColor(16, 185, 129),
    "warning": RGBColor(245, 158, 11),
    "error": RGBColor(239, 68, 68),
    "info": RGBColor(59, 130, 246),
    "background": RGBColor(255, 255, 255),
    "background_alt": RGBColor(249, 250, 251),
    "royal_blue": RGBColor(65, 105, 225),
    "medium_purple": RGBColor(147, 112, 219),
    "dark_blue": RGBColor(26, 43, 60),
    "teal": RGBColor(20, 184, 166),
    "emerald": RGBColor(16, 185, 129),
    "gradient_start": RGBColor(65, 105, 225),
    "gradient_end": RGBColor(147, 112, 219),
    "activity_purple": RGBColor(139, 92, 246),
    "activity_blue": RGBColor(37, 99, 235),
    "activity_green": RGBColor(16, 185, 129),
    "activity_orange": RGBColor(249, 115, 22),
}

GLOBAL_LANG = "en"

LABELS = {
    "en": {
        "learningOutcomes": "Learning Outcomes",
        "byTheEnd": "By the end of this {contentType}, you will be able to:",
        "keyTerms": "Key Terms & Concepts",
        "agenda": "Agenda",
        "continued": " (continued)",
        "agendaContinued": " (continued {idx}/{total})",
        "introduction": "Introduction",
        "mainContent": "Main Content",
        "activities": "Activities",
        "testYourKnowledge": "Test Your Knowledge",
        "quizQuestions": "Quiz Questions ({count})",
        "discussionQuestions": "Discussion Questions ({count})",
        "additionalResources": "Additional Resources",
        "furtherReadings": "Further Readings & Resources",
        "activity": "Activity {num}: {title}",
        "materialsSuffix": "(Materials)",
        "type": "Type",
        "duration": "Duration",
        "instructions": "Instructions:",
        "materialsNeeded": "Materials needed:",
        "notesAvailable": "Notes Available",
        "quizQuestion": "Quiz Question {num}",
        "quizAnswer": "Quiz Answer {num}",
        "question": "Question: {text}",
        "correctAnswer": "Correct Answer:",
        "explanation": "Explanation:",
        "groupDiscussion": "Group Discussion:",
        "groupInstruction": "Discuss this question with your group and prepare to share your thoughts with the class.",
        "facilitatorGuidance": "Facilitator Guidance: Question {num}",
        "author": "Author:",
        "term": "Term",
        "definition": "Definition",
        "discussionQuestion": "Discussion Question {num}",
        "thankYou": "Thank You!",
        "presentation": "Presentation:",
        "facilitationNotesSummary": "Facilitation Notes Summary",
        "continuedNextSlide": "Continued on next slide...",
        "facilitationNotesLabel": "Facilitation Notes:",
        "learningObjectiveLabel": "Learning Objective:",
        "successCriteriaLabel": "Success criteria:",
        "untitledPresentation": "Untitled Presentation",
        "untitledReading": "Untitled Reading",
        "untitledActivity": "Untitled Activity",
        "unknownAuthor": "Unknown Author",
        "contentTypeNames": {
            "lecture": "Lecture",
            "tutorial": "Tutorial",
            "workshop": "Workshop",
        },
        "difficultyNames": {
            "introductory": "Introductory Level",
            "intermediate": "Intermediate Level",
            "advanced": "Advanced Level",
        },
    },
    "id": {
        "learningOutcomes": "Capaian Pembelajaran",
        "byTheEnd": "Di akhir {contentType} ini, Anda akan dapat:",
        "keyTerms": "Istilah Kunci & Konsep",
        "agenda": "Agenda",
        "continued": " (lanjutan)",
        "agendaContinued": " (lanjutan {idx}/{total})",
        "introduction": "Pendahuluan",
        "mainContent": "Konten Utama",
        "activities": "Aktivitas",
        "testYourKnowledge": "Uji Pengetahuan Anda",
        "quizQuestions": "Soal Kuis ({count})",
        "discussionQuestions": "Pertanyaan Diskusi ({count})",
        "additionalResources": "Sumber Tambahan",
        "furtherReadings": "Bacaan Lanjutan & Sumber",
        "activity": "Aktivitas {num}: {title}",
        "materialsSuffix": "(Perlengkapan)",
        "type": "Jenis",
        "duration": "Durasi",
        "instructions": "Instruksi:",
        "materialsNeeded": "Perlengkapan yang dibutuhkan:",
        "notesAvailable": "Catatan Tersedia",
        "quizQuestion": "Soal Kuis {num}",
        "quizAnswer": "Jawaban Kuis {num}",
        "question": "Pertanyaan: {text}",
        "correctAnswer": "Jawaban Benar:",
        "explanation": "Penjelasan:",
        "groupDiscussion": "Diskusi Kelompok:",
        "groupInstruction": "Diskusikan pertanyaan ini dengan kelompok Anda dan siapkan untuk berbagi pendapat dengan kelas.",
        "facilitatorGuidance": "Panduan Fasilitator: Pertanyaan {num}",
        "author": "Penulis:",
        "term": "Istilah",
        "definition": "Definisi",
        "discussionQuestion": "Pertanyaan Diskusi {num}",
        "thankYou": "Terima kasih!",
        "presentation": "Presentasi:",
        "facilitationNotesSummary": "Ringkasan Catatan Fasilitasi",
        "continuedNextSlide": "Bersambung di slide berikutnya...",
        "facilitationNotesLabel": "Catatan Fasilitasi:",
        "learningObjectiveLabel": "Tujuan Pembelajaran:",
        "successCriteriaLabel": "Kriteria keberhasilan:",
        "untitledPresentation": "Presentasi Tanpa Judul",
        "untitledReading": "Bacaan Tanpa Judul",
        "untitledActivity": "Aktivitas Tanpa Judul",
        "unknownAuthor": "Penulis Tidak Diketahui",
        "contentTypeNames": {
            "lecture": "Kuliah",
            "tutorial": "Tutorial",
            "workshop": "Lokakarya",
        },
        "difficultyNames": {
            "introductory": "Tingkat Dasar",
            "intermediate": "Tingkat Menengah",
            "advanced": "Tingkat Lanjutan",
        },
    },
}

BULLET_MARKERS = ["•", "*", "-", "○", "◦", "▪", "▫", "◆", "◇", "►", "▻", "▶", "▷"]
SUB_BULLET_MARKERS = ["-", "○", "◦", "▪", "▫"]
