import { Lang } from '@/lib/utils/lang'

export function getDocxLabels(language: Lang) {
  if (language === 'id') {
    return {
      confidential: 'SULIT',
      rubricTitle: 'RUBRIK PENILAIAN',
      gradingScale:
        'Skala Penilaian: 1 - Sangat Kurang, 2 - Cukup, 3 - Sedang, 4 - Baik, 5 - Sangat Baik.',
      reportSection: 'LAPORAN (55%)',
      demoSection: 'PRESENTASI DEMO (30%)',
      individualSection: 'KONTRIBUSI INDIVIDU (15%)',
      criteria: 'Kriteria',
      excellentHeader: 'Sangat Baik (5)\nA, A-',
      goodHeader: 'Baik (4)\nB+, B, B-',
      averageHeader: 'Sedang (3)\nC+, C',
      acceptableHeader: 'Cukup (2)\nC-, D+',
      poorHeader: 'Sangat Kurang (1)\nD, D-, F',
      excellentDefault: 'Kinerja sangat baik',
      goodDefault: 'Kinerja baik',
      averageDefault: 'Kinerja sedang',
      acceptableDefault: 'Kinerja cukup',
      poorDefault: 'Kinerja sangat kurang',
      projectInformation: 'INFORMASI PROYEK',
      projectDescription: 'DESKRIPSI PROYEK',
      semester: 'Semester',
      academicYear: 'Tahun Akademik',
      submissionDeadline: 'Batas Pengumpulan',
      groupSize: 'Ukuran Kelompok',
      membersPerGroup: 'anggota per kelompok',
      duration: 'Durasi',
      modelAnswerGuidelines: 'JAWABAN CONTOH/PANDUAN',
      modelAnswer: 'Jawaban Model',
      markingCriteria: 'Kriteria Penilaian',
      markAllocation: 'Alokasi Nilai',
      instructions1: 'Instruksi: Pastikan kertas ujian ini lengkap sebelum Anda memulai ujian.',
      instructions2Prefix: 'Instruksi: Jawab semua',
      questions: 'pertanyaan',
      instructions3: 'Anda dapat menjawab pertanyaan dalam Bahasa Inggris atau Bahasa Indonesia.',
      instructions4: 'Jika terjadi perbedaan, versi Bahasa Inggris yang digunakan.',
      defaultContentQuality: 'Kualitas Konten',
      defaultContentQualityDesc: 'Kedalaman dan akurasi konten',
      defaultImplementation: 'Implementasi',
      defaultImplementationDesc: 'Kualitas implementasi',
      defaultPresentation: 'Presentasi',
      defaultPresentationDesc: 'Kejelasan dan organisasi',
      defaultIndividualContribution: 'Kontribusi Individu',
      defaultIndividualContributionDesc: 'Partisipasi dan kontribusi individu',
      quizInstruction:
        'Instruksi: Kuis ini terdiri dari beberapa pertanyaan. Bacalah setiap pertanyaan dengan cermat dan berikan jawaban yang benar.',
      studentName: 'Nama Mahasiswa',
      dateLabel: 'Tanggal',
    }
  }
  return {
    confidential: 'CONFIDENTIAL',
    rubricTitle: 'ASSESSMENT RUBRIC',
    gradingScale: 'Grading Scale: 1 - Poor, 2 - Acceptable, 3 - Average, 4 - Good, 5 - Excellent.',
    reportSection: 'REPORT (55%)',
    demoSection: 'DEMO PRESENTATION (30%)',
    individualSection: 'INDIVIDUAL CONTRIBUTION (15%)',
    criteria: 'Criteria',
    excellentHeader: 'Excellent (5)\nA, A-',
    goodHeader: 'Good (4)\nB+, B, B-',
    averageHeader: 'Average (3)\nC+, C',
    acceptableHeader: 'Acceptable (2)\nC-, D+',
    poorHeader: 'Poor (1)\nD, D-, F',
    excellentDefault: 'Excellent performance',
    goodDefault: 'Good performance',
    averageDefault: 'Average performance',
    acceptableDefault: 'Acceptable performance',
    poorDefault: 'Poor performance',
    projectInformation: 'PROJECT INFORMATION',
    projectDescription: 'PROJECT DESCRIPTION',
    semester: 'Semester',
    academicYear: 'Academic Year',
    submissionDeadline: 'Submission Deadline',
    groupSize: 'Group Size',
    membersPerGroup: 'members per group',
    duration: 'Duration',
    modelAnswerGuidelines: 'MODEL ANSWER/GUIDELINES',
    modelAnswer: 'Model Answer',
    markingCriteria: 'Marking Criteria',
    markAllocation: 'Mark Allocation',
    instructions1:
      'Instructions: Please ensure that this examination paper is complete before you begin the examination.',
    instructions2Prefix: 'Instructions: Answer all',
    questions: 'questions',
    instructions3: 'You may answer the questions either in English or in Bahasa Indonesia.',
    instructions4: 'In the event of any discrepancies, the English version shall be used.',
    defaultContentQuality: 'Content Quality',
    defaultContentQualityDesc: 'Depth and accuracy of content',
    defaultImplementation: 'Implementation',
    defaultImplementationDesc: 'Quality of implementation',
    defaultPresentation: 'Presentation',
    defaultPresentationDesc: 'Clarity and organization',
    defaultIndividualContribution: 'Individual Contribution',
    defaultIndividualContributionDesc: 'Individual participation and contribution',
    quizInstruction:
      'Instructions: This quiz contains multiple questions. Read each question carefully and provide the correct answers.',
    studentName: 'Student Name',
    dateLabel: 'Date',
  }
}
