// Centralized labels and language definitions for PDF generation
export type Lang = 'en' | 'id'

export const LABELS: Record<Lang, Record<string, string>> = {
  en: {
    generatedOn: 'Generated on',
    contentType: 'Content Type',
    difficultyLevel: 'Difficulty Level',
    introduction: 'Introduction',
    learningOutcomes: 'Learning Outcomes',
    keyTerms: 'Key Terms',
    slides: 'Slides',
    speakerNotes: 'Speaker Notes:',
    activities: 'Activities',
    type: 'Type',
    duration: 'Duration',
    instructions: 'Instructions:',
    materialsNeeded: 'Materials Needed:',
    assessmentIdeas: 'Assessment Ideas',
    quizAssessments: 'Quiz Assessments',
    exampleQuestions: 'Example Questions',
    correctAnswer: 'Correct Answer:',
    explanation: 'Explanation:',
    discussionAssessments: 'Discussion Assessments',
    discussionTopics: 'Discussion Topics',
    discussionGuidance: 'Discussion Guidance:',
    assessmentCriteria: 'Assessment Criteria:',
    pointAllocation: 'Point Allocation:',
    criteria: 'Criteria',
    weight: 'Weight',
    component: 'Component',
    points: 'Points',
    otherAssessments: 'Other Assessments',
    modelAnswer: 'Model Answer:',
    furtherReadings: 'Further Readings',
    furtherReadingsAndResources: 'Further Readings & Resources',
    author: 'Author:',
    slide: 'Slide',
  },
  id: {
    generatedOn: 'Dibuat pada',
    contentType: 'Jenis Konten',
    difficultyLevel: 'Tingkat Kesulitan',
    introduction: 'Pendahuluan',
    learningOutcomes: 'Capaian Pembelajaran',
    keyTerms: 'Istilah Kunci',
    slides: 'Slide',
    speakerNotes: 'Catatan Pembicara:',
    activities: 'Aktivitas',
    type: 'Jenis',
    duration: 'Durasi',
    instructions: 'Instruksi:',
    materialsNeeded: 'Perlengkapan yang Dibutuhkan:',
    assessmentIdeas: 'Ide Penilaian',
    quizAssessments: 'Penilaian Kuis',
    exampleQuestions: 'Contoh Pertanyaan',
    correctAnswer: 'Jawaban Benar:',
    explanation: 'Penjelasan:',
    discussionAssessments: 'Penilaian Diskusi',
    discussionTopics: 'Topik Diskusi',
    discussionGuidance: 'Panduan Diskusi:',
    assessmentCriteria: 'Kriteria Penilaian:',
    pointAllocation: 'Alokasi poin:',
    criteria: 'Kriteria',
    weight: 'Bobot',
    component: 'Komponen',
    points: 'Poin',
    otherAssessments: 'Penilaian Lainnya',
    modelAnswer: 'Jawaban Model:',
    furtherReadings: 'Bacaan Lanjutan',
    furtherReadingsAndResources: 'Bacaan Lanjutan & Sumber',
    author: 'Penulis:',
    slide: 'Slide',
  },
}
